// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/docs": {
            "get": {
                "description": "Serves the interactive API reference UI",
                "produces": [
                    "text/html"
                ],
                "tags": [
                    "System"
                ],
                "summary": "API Documentation",
                "responses": {
                    "200": {
                        "description": "HTML page",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/events/stream": {
            "get": {
                "description": "Server-sent events stream for real-time wagon movement updates",
                "produces": [
                    "text/event-stream"
                ],
                "tags": [
                    "Events"
                ],
                "summary": "Events Stream",
                "responses": {
                    "200": {
                        "description": "SSE stream",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/fleet/status": {
            "get": {
                "description": "Returns wagon counts by type and status, plus average empty-run km for today",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Wagon"
                ],
                "summary": "Fleet Status",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controller.fleetStatusResponse"
                        }
                    },
                    "500": {
                        "description": "Failed to retrieve fleet status",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Returns 200 OK when the service is healthy",
                "tags": [
                    "System"
                ],
                "summary": "Health Check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/metrics": {
            "get": {
                "description": "Returns financial and operational metrics: empty run costs, revenue, cost saved vs naive",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Metrics"
                ],
                "summary": "Financial Metrics",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/usecase.MetricsOutput"
                        }
                    },
                    "500": {
                        "description": "Failed to retrieve metrics",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/orders": {
            "get": {
                "description": "Retrieves all orders and their current status",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Order"
                ],
                "summary": "List Orders",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controller.listOrdersResponse"
                        }
                    },
                    "500": {
                        "description": "Failed to retrieve orders",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "description": "Places a new wagon order for a client",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Order"
                ],
                "summary": "Create Order",
                "parameters": [
                    {
                        "description": "Order payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/usecase.CreateOrderInput"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/entity.Order"
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Failed to create order",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/simulation": {
            "get": {
                "description": "Returns current simulation clock state",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Simulation"
                ],
                "summary": "Simulation Status",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controller.simStatusResponse"
                        }
                    }
                }
            }
        },
        "/stations": {
            "get": {
                "description": "Retrieves all stations and active edges forming the railway graph",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Station"
                ],
                "summary": "List Stations",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controller.listStationsResponse"
                        }
                    },
                    "500": {
                        "description": "Failed to retrieve stations",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/trains": {
            "get": {
                "description": "Returns a list of all active trains",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Train"
                ],
                "summary": "List Active Trains",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/entity.Train"
                            }
                        }
                    },
                    "500": {
                        "description": "Failed to list trains",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "description": "Creates a new train from a list of wagons and a route",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Train"
                ],
                "summary": "Create Train",
                "parameters": [
                    {
                        "description": "Train payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controller.CreateTrainInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entity.Train"
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Failed to create train",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/trains/{id}": {
            "get": {
                "description": "Returns details of a specific train",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Train"
                ],
                "summary": "Get Train Details",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Train ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entity.Train"
                        }
                    },
                    "400": {
                        "description": "Invalid train id",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Train not found",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/trains/{id}/dispatch": {
            "post": {
                "description": "Dispatches a forming train to start its journey",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Train"
                ],
                "summary": "Dispatch Train",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Train ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Invalid train id",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Failed to dispatch train",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/wagons": {
            "get": {
                "description": "Retrieves all wagons and their current status",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Wagon"
                ],
                "summary": "List Wagons",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controller.listWagonsResponse"
                        }
                    },
                    "500": {
                        "description": "Failed to retrieve wagons",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "controller.CreateTrainInput": {
            "type": "object",
            "properties": {
                "route": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "wagonIds": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "controller.edgeResponse": {
            "type": "object",
            "properties": {
                "distanceKm": {
                    "type": "integer"
                },
                "from": {
                    "type": "string"
                },
                "to": {
                    "type": "string"
                }
            }
        },
        "controller.fleetStatusResponse": {
            "type": "object",
            "properties": {
                "avgEmptyRunKmToday": {
                    "type": "number"
                },
                "byType": {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/usecase.WagonTypeStatus"
                    }
                },
                "totalWagons": {
                    "type": "integer"
                }
            }
        },
        "controller.listOrdersResponse": {
            "type": "object",
            "properties": {
                "orders": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entity.Order"
                    }
                }
            }
        },
        "controller.listStationsResponse": {
            "type": "object",
            "properties": {
                "edges": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/controller.edgeResponse"
                    }
                },
                "stations": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/controller.stationResponse"
                    }
                }
            }
        },
        "controller.listWagonsResponse": {
            "type": "object",
            "properties": {
                "statusCounts": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "integer"
                    }
                },
                "wagons": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entity.Wagon"
                    }
                }
            }
        },
        "controller.simStatusResponse": {
            "type": "object",
            "properties": {
                "currentHour": {
                    "type": "integer"
                },
                "displayTime": {
                    "type": "string"
                },
                "speed": {
                    "type": "integer"
                }
            }
        },
        "controller.stationResponse": {
            "type": "object",
            "properties": {
                "lat": {
                    "type": "number"
                },
                "lng": {
                    "type": "number"
                },
                "name": {
                    "type": "string"
                },
                "stationId": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "entity.Order": {
            "type": "object",
            "properties": {
                "clientName": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "desiredDate": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "quantity": {
                    "type": "integer"
                },
                "stationToId": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/entity.OrderStatus"
                },
                "type": {
                    "$ref": "#/definitions/entity.OrderType"
                },
                "wagonType": {
                    "$ref": "#/definitions/entity.WagonType"
                }
            }
        },
        "entity.OrderStatus": {
            "type": "string",
            "enum": [
                "pending",
                "matched",
                "fulfilled",
                "cancelled"
            ],
            "x-enum-varnames": [
                "Pending",
                "Matched",
                "Fulfilled",
                "Cancelled"
            ]
        },
        "entity.OrderType": {
            "type": "string",
            "enum": [
                "external",
                "internal"
            ],
            "x-enum-varnames": [
                "External",
                "Internal"
            ]
        },
        "entity.Train": {
            "type": "object",
            "properties": {
                "arrivedAt": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "departedAt": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "locomotiveId": {
                    "type": "string"
                },
                "nextStationId": {
                    "type": "string"
                },
                "route": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "sourceStationId": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/entity.TrainStatus"
                },
                "stepIndex": {
                    "type": "integer"
                },
                "wagonIds": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "entity.TrainStatus": {
            "type": "string",
            "enum": [
                "forming",
                "in_transit",
                "arrived"
            ],
            "x-enum-varnames": [
                "TrainForming",
                "TrainInTransit",
                "TrainArrived"
            ]
        },
        "entity.Wagon": {
            "type": "object",
            "properties": {
                "currentStationId": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "lastUnloadTime": {
                    "type": "string"
                },
                "number": {
                    "type": "string"
                },
                "stateUntilHour": {
                    "type": "integer"
                },
                "status": {
                    "$ref": "#/definitions/entity.WagonStatus"
                },
                "type": {
                    "$ref": "#/definitions/entity.WagonType"
                }
            }
        },
        "entity.WagonStatus": {
            "type": "string",
            "enum": [
                "loaded",
                "empty_moving",
                "idle",
                "maintenance",
                "in_train"
            ],
            "x-enum-varnames": [
                "Loaded",
                "EmptyMoving",
                "Idle",
                "Maintenance",
                "InTrain"
            ]
        },
        "entity.WagonType": {
            "type": "string",
            "enum": [
                "gondola",
                "grain_hopper",
                "cement_hopper"
            ],
            "x-enum-varnames": [
                "Gondola",
                "GrainHopper",
                "CementHopper"
            ]
        },
        "usecase.CreateOrderInput": {
            "type": "object",
            "properties": {
                "clientName": {
                    "type": "string"
                },
                "desiredDate": {
                    "type": "string"
                },
                "quantity": {
                    "type": "integer"
                },
                "stationToId": {
                    "type": "string"
                },
                "type": {
                    "$ref": "#/definitions/entity.OrderType"
                },
                "wagonType": {
                    "$ref": "#/definitions/entity.WagonType"
                }
            }
        },
        "usecase.MetricsOutput": {
            "type": "object",
            "properties": {
                "avgEmptyRunKm": {
                    "type": "number"
                },
                "costSavedVsNaive": {
                    "type": "number"
                },
                "matchRate": {
                    "type": "number"
                },
                "naiveCost": {
                    "type": "number"
                },
                "optimizedCost": {
                    "type": "number"
                },
                "ordersMatched": {
                    "type": "integer"
                },
                "ordersUnmatched": {
                    "type": "integer"
                },
                "totalCostEmptyRun": {
                    "type": "integer"
                },
                "totalDeliveredAssignments": {
                    "type": "integer"
                },
                "totalEmptyRunKm": {
                    "type": "integer"
                },
                "totalLoadedRunKm": {
                    "type": "integer"
                },
                "totalRevenue": {
                    "type": "integer"
                }
            }
        },
        "usecase.WagonTypeStatus": {
            "type": "object",
            "properties": {
                "emptyMoving": {
                    "type": "integer"
                },
                "idle": {
                    "type": "integer"
                },
                "loaded": {
                    "type": "integer"
                },
                "maintenance": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.2.5",
	Host:             "",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "Empty Runner Buster API",
	Description:      "This is the API documentation for the Empty Runner Buster application",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
