basePath: /api
host: localhost:8080
info:
  contact: {}
  description: This is the API documentation for the Empty Runner Buster application
  title: Empty Runner Buster API
  version: "1.0"
paths:
  /health:
    get:
      consumes:
      - application/json
      description: Checks the health of the API
      produces:
      - application/json
      responses: {}
      summary: Health Check
      tags:
      - System
swagger: "2.0"
